# Generated by Django 3.2.4 on 2022-09-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220904_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='cpasswd',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
